name: epub傍点变换nuitka编译exe

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:

    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: 安装依赖
      run: |
        pip install nuitka
        pip install beautifulsoup4
        pip install loguru
        pip install lxml
        pip install tkinterdnd2

    - name: 编译EXE文件
      run: |
        echo Yes | nuitka --standalone --follow-imports --onefile --windows-icon-from-ico=note.ico --enable-plugin=tk-inter sesame-to-ruby.py
      
    - name: 列出当前目录的文件列表
      shell: pwsh
      run: Get-ChildItem -Force

    - name: 上传EXE文件
      uses: actions/upload-artifact@v4
      with:
        name: sesame-to-ruby
        path: ./sesame-to-ruby.exe
